site_name: EMI
nav:
    - Principal:
        - Introducción: cuerpo/introduccion.md
        - Justificación: cuerpo/justificacion.md
    - Calibración: 
        - Determinación del proceso de caminata aleatoria: calibracion/Determinación proceso caminata aleatoria.md
        - Calibración de varianza del proceso de caminata aleatoria: calibracion/Calibración varianza RW.md
        - Selección del número de simulaciones: calibracion/Selección simulaciones.md
        - Selección de la medida de evaluación: calibracion/Determinación medida evaluación.md
        - Remuestreo con block bootstrap: calibracion/Remuestreo block bootstrap.md

theme: 
    name: readthedocs
    highlightjs: true
    hljs_style: "Tomorrow"
    hljs_languages:
        - matlab
        - python

markdown_extensions:
    - pymdownx.arithmatex
    - toc:
        baselevel: 2
        permalink: True

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML